version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_conversor
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: conversor-app
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - redis
