[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-v --cov=app --cov-report=term-missing --cov-fail-under=90"
testpaths = ["tests"]
